Initial API Documentation
bml2238/senior-project pull request #13
Opened 2023-11-01 17:46 UTC by bml2238

Includes documentation for all proposed API calls for the student workflow, excluding login/authentication calls.

The actual file that has the API docs is frontend/crd/src/app/api-documentations/api.json

2023-11-01 20:47 UTC, jts7382 commented on frontend/crd/src/app/api-documentations/api-documentations.component.spec.ts
should we delete this file? We don't really need to unit test this, but it seems to be passing and getting 100% coverage so I guess its fine if we leave it

2023-11-01 20:59 UTC, jts7382 requested changes

2023-11-01 20:59 UTC, jts7382 commented on frontend/crd/src/app/api-documentations/api.json
> +    "description": "API description in Markdown.",
```suggestion
    "title": "Career Readiness Dashboard API",
    "description": "API documentation for the Career Readiness Dashboard 2023-2024 senior project",
```

2023-11-01 20:59 UTC, jts7382 commented on frontend/crd/src/app/api-documentations/api.json
> +        "responses": {
can we add some schemas to the responses? see https://swagger.io/docs/specification/describing-responses/

2023-11-02 21:46 UTC, bml2238 commented on frontend/crd/src/app/api-documentations/api-documentations.component.spec.ts
we may want to unit test in the future, so it might be better to keep it. im more of a digital hoarder so if you have any thoughts please lmk

2023-11-06 15:18 UTC, jts7382 approved these changes
This looks great

2023-11-06 19:35 UTC, rcb2957 approved these changes
The changes look fine.

2023-11-06 19:35 UTC, merged