Database schema
bml2238/senior-project pull request #25
Opened 2023-11-13 21:44 UTC by jts7382

Database connection setup. Event and Milestone Repositories are working. Milestones are not tied to tasks/Events yet, may need to change the way they are mapped. Also, no data in the database yet because there are not migration scripts.

2023-11-13 23:44 UTC, BasketOfEggs commented on backend/src/main/java/com/senior/project/backend/Activity/EventRepository.java
> +    // additional query methods if needed
This is beautiful to see. Should we store the old testing data in a separate file for testing purposes?

2023-11-13 23:44 UTC, BasketOfEggs commented on backend/src/main/java/com/senior/project/backend/domain/Artifact.java
> +	private String name;
fix code indents and style

2023-11-13 23:44 UTC, BasketOfEggs commented on backend/src/main/java/com/senior/project/backend/domain/Assignment.java
> +	private int studentID;
Same here

2023-11-13 23:45 UTC, BasketOfEggs commented on backend/src/main/java/com/senior/project/backend/domain/Faculty.java
> +	private String userID;
Fix indents

2023-11-13 23:45 UTC, BasketOfEggs commented on backend/src/main/java/com/senior/project/backend/domain/Major.java
> +	private String name;
Fix indents

2023-11-13 23:46 UTC, BasketOfEggs commented on backend/src/main/java/com/senior/project/backend/domain/Student.java
> +	private int userID;
It looks like a consistent thing, so scanning through the domain classes to fix it would be worth it. Low priority though, its just styling

2023-11-13 23:47 UTC, BasketOfEggs commented on backend/src/test/java/com/senior/project/backend/Activity/EventHandlerTest.java
> +    @InjectMocks
didn't know this was a thing, very cool

2023-11-13 23:49 UTC, BasketOfEggs requested changes
See above comments

2023-11-14 23:49 UTC, BasketOfEggs approved these changes

2023-11-15 00:23 UTC, bml2238 approved these changes

2023-11-15 00:25 UTC, merged