basic comments
bml2238/senior-project pull request #68
Opened 2024-03-05 21:23 UTC by bml2238

files i did not document:
ArtifactHandler.java
artifact.service.ts
image-upload.component.ts
user-page.component.ts (already had comments, but not official ones)

2024-03-06 22:06 UTC, jts7382 requested changes

2024-03-06 22:06 UTC, jts7382 commented on frontend/crd/src/app/portfolio/portfolio.component.ts
> +   * Opens the file select modal
```suggestion
   * Opens the Submission Modal
```

2024-03-06 22:06 UTC, jts7382 commented on frontend/crd/src/app/portfolio/portfolio.component.ts
> +   * The student is able to upload their resume directly from the portfolio
```suggestion
   * Grabs the Student's artifacts to be displayed.
   * Currently just grabs the resume
```

2024-03-06 22:06 UTC, jts7382 commented on frontend/crd/src/app/util/task.service.ts
> +   * it makes a request to the backend.
```suggestion
   * it makes a request to the backend.
   * @param forceRefresh forces the cache to update by sending the request again
```

2024-03-07 01:28 UTC, bml2238 commented on frontend/crd/src/app/admin/task-main-page/task-main-page.component.ts
> -      //TODO: successful save popup?
there are save popups in the modals themselves but we could add one on the main page later

2024-03-07 22:47 UTC, JohnLDavidson approved these changes

2024-03-07 23:24 UTC, jts7382 approved these changes

2024-03-07 23:24 UTC, merged